name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Buildozer
        run: |
          pip install --user --upgrade buildozer
          pip install --user --upgrade Cython==0.29.33

      - name: Build with Buildozer
        run: |
          # هذه الخطوة ستقوم بتثبيت التبعيات وبناء التطبيق
          buildozer android debug
